services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: hiephanguyen01
      POSTGRES_PASSWORD: hahiep01
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hiephanguyen01 -d app"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  postgres_data:
